# Generated by Django 4.2.7 on 2024-02-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helping_hands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipspage',
            name='text8',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='partnershipspage',
            name='text5',
            field=models.TextField(default='', max_length=100),
        ),
    ]
