# Generated by Django 4.2.7 on 2024-02-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helping_hands', '0003_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.AddField(
            model_name='donation',
            name='user_id',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
